@startuml 表设计1

!include ../common.cuml

skinparam backgroundColor #DDDDDD

namespace 问卷{

        Table(t_survey, "问卷表") {
        }
        
        Table(t_survey_question, "问卷问题表") {
        }
        
        Table(t_survey_question_options, "问卷问题选项表") {
        }

        t_survey "id" ---> "survey_id" t_survey_question
        t_survey_question "id" ---> "question_id" t_survey_question_options

}

namespace 问卷结果{

        Table(t_survey_answer, "问卷结果父表") {
        }

        Table(t_survey_question_answer, "问卷结果子表") {
        }

        t_survey_answer "id" ---> "survey_answer_id" t_survey_question_answer

}


问卷.t_survey "id\n" <--[#blue,dashed]-- "survey_id" 问卷结果.t_survey_answer : 根据答案找问卷 <

问卷.t_survey_question "id" <--[#blue,dashed]-- "question_id" 问卷结果.t_survey_question_answer : 根据问题id找问题详情 <

问卷.t_survey_question_options "id" <--[#blue,dashed]-- "answer_value" 问卷结果.t_survey_question_answer : 根据答案找答案详情 <

namespace 在线业务{

Table(t_live_order_course_survey, "问卷表（业务关联表）") {
}

}

在线业务.t_live_order_course_survey "survey_id" --[#blue,dashed]--> "id" 问卷.t_survey : 找问卷的题目 >

在线业务.t_live_order_course_survey "survey_answer_id" -[#blue,dashed]-> "id" 问卷结果.t_survey_answer : 找问卷的答案 >

 
@enduml