@startmindmap share-1

+ <b>设计规约</b>

-- 阿里巴巴Java开发手册-设计规约
--- 规约级别
----_ 强制
----_ 推荐
----_ 参考
--- 设计规约
----_ 有6条强制级别
----_ 文档
----_ 用例图
----_ 状态图
----_ 时序图
----_ 类图
----_ 活动图

-- 基于PlantUML的绘图
--- 用例图
--- 状态图
--- 时序图
--- 类图
--- 活动图

-- 敏捷开发-设计文档方面
---_ 小版本发布,小版本发布带来的是不复杂的设计.
---_ 轻文档的开发模式,但轻文档≠无文档,奉行的是持续设计,\n需要不断的设计,改善(重构),交付.


++ 文档编写
+++ 目前的问题
++++_ 更新不及时:同一功能的多版本修改,导致旧版本文档失效
++++_ 描述不清晰:设计文档格式未统一,编写格式繁多
++++_ 文档与代码不符:编码中发现的设计错误,编码前写的设计文档未更新
+++ 解决方案
++++ 更新不及时
+++++_ 技术优化:文档中关联该功能最后一次修改的文档
++++ 描述不清晰
+++++_ 定制设计文档模板,按照通用的格式编写
++++ 文档与代码不符
+++++_ 编码前写设计文档初稿,编码完成后补充成为终稿
+++ 我的方案(见图二)
++ 文档方案头脑风暴

@endmindmap


@startmindmap share-2
+ 文档结构
++_ 引言
+++_ 背景(解释为什么要写这个功能)
+++_ 定义(定义某些术语)
+++_ 参考资料(关联同功能最后一次更改文档)
++_ 总体设计
+++_ 功能概述(介绍有哪些功能)
+++_ 相关图表(活动,用例,时序,类,状态图)
+++_ 数据表设计(表字段,索引,表间关系)
+++_ 功能详情(业务逻辑)
+++_ 相关接口(关联版本的接口文档)
++_ 其他方案及其对比
+++_ PlanB
+++_ ...
++_ 测试要点即上线计划\n- 关联到发布流程
@endmindmap